AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Weatherio — HTTP API ($default stage) on Node.js 20

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: nodejs20.x
  # NOTE: Remove Globals.Api (that was only for REST APIs)

Resources:
  # --- HTTP API with no visible stage in the URL ---
  WeatherioHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: [GET,POST,PUT,DELETE,OPTIONS]
        AllowHeaders: ['*']

  # --- Lambda function (unchanged handler/code) wired to HTTP API ---
  WeatherApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      CodeUri: .
      Runtime: nodejs20.x
      Environment:
        Variables:
          # Consider moving this to Secrets Manager later
          MONGO_URI: "mongodb+srv://corpgroupbeintern_db_user:wIUfjZFqCPO0JvIh@cluster0.ve8fl4r.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      Events:
        Root:
          Type: HttpApi
          Properties:
            ApiId: !Ref WeatherioHttpApi
            Path: /
            Method: ANY
            PayloadFormatVersion: '2.0'
        Proxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref WeatherioHttpApi
            Path: /{proxy+}
            Method: ANY
            PayloadFormatVersion: '2.0'

Outputs:
  HttpApiUrl:
    Description: "HTTP API invoke URL (no stage suffix)"
    Value: !Sub "https://${WeatherioHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
