Globals:
  Function:
    Timeout: 20        # was 10
    MemorySize: 512
    Runtime: nodejs18.x

Resources:
  WeatherApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      CodeUri: .
      Runtime: nodejs18.x
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          # IMPORTANT when running in Docker: use host.docker.internal to reach your host DB
          MONGO_URI: "mongodb+srv://corpgroupbeintern_db_user:wIUfjZFqCPO0JvIh@cluster0.ve8fl4r.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
